/* 0. Imports */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import TopNav from "./ui/TopNav";
import SideNav from "./ui/SideNav";

/* 1. Font Configuration */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* 2. Metadata */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/* 3. Root-Layout Components */
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      
      {/* Body Class */}
      <body className={`${geistSans.variable} ${geistMono.variable} w-dvw overflow-x-hidden`}>
        <header>
          <TopNav />
          <SideNav />
        </header>
        {/* Main Content */}
        <main className="">
          {children}
        </main>
      </body>
    </html>
  );
}
