/* 0. Imports */
import type { Metadata } from "next";
import { Space_Grotesk, Rock_Salt } from "next/font/google"; // Import Rock Salt
import "./globals.css";

import TopNav from "@components/layout/TopNav";

/* 1. Font Configuration */
const spaceGrotesk = Space_Grotesk({
  weight: ['300', '700'],
  style: ['normal'],
  subsets: ['latin'],
});

const rockSalt = Rock_Salt({
  weight: '400', // Rock Salt only has 400 weight
  style: 'normal',
  subsets: ['latin'],
});

/* 2. Metadata */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/* 3. Root-Layout Components */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* Body Class */}
      <body
        className={`${spaceGrotesk.className} w-dvw h-dvh overflow-x-hidden`}
      >
        <header>
          <TopNav />
          {/* <SideNav /> */}
        </header>
        {/* Main Content */}
        <main className="w-full h-full">{children}</main>
      </body>
    </html>
  );
}
